// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRequest(arg1, arg2) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetCollectionsFrom(arg1) {
  return window['go']['main']['App']['GetCollectionsFrom'](arg1);
}

export function PromptOpenFile() {
  return window['go']['main']['App']['PromptOpenFile']();
}

export function PromptOpenWorkspace() {
  return window['go']['main']['App']['PromptOpenWorkspace']();
}

export function UpdateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2, arg3);
}
