// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCollection(arg1:string,arg2:string):Promise<void>;

export function CreateRequest(arg1:string,arg2:models.APIRequest):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvForCollection(arg1:string,arg2:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function ExecuteRequest(arg1:models.APIRequest):Promise<models.APIResponse>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetCollectionsFrom(arg1:string):Promise<Array<models.Collection>>;

export function LoadEnvForCollection(arg1:string):Promise<Record<string, string>>;

export function PromptOpenFile():Promise<models.Collection>;

export function PromptOpenWorkspace():Promise<string>;

export function PromptSaveFilePath(arg1:string,arg2:string):Promise<string>;

export function SaveEnvForCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateRequest(arg1:string,arg2:string,arg3:models.APIRequest):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
